### ISSUE TITLE
No rules generated

### ISSUE THREAD

**Issue by MaverickLegacy** [nupur1492/RProjects#1]
I ran the code on the same data given on the website but after executing the **_apriori_** command  the number of rules generated is zero.

**Comment by fkaptan** [comment]
i have the same problem too

**Comment by nupur1492** [comment]
Thank you for bringing it to my notice. Shall post the fix soon.

**Comment by mispispis** [comment]
@nupur1492 the problem continues.

**Comment by gklabs** [comment]
No rules generated

**Comment by nupur1492** [comment]
Hi everyone, I am sorry for the delay in fixing the problem. I have created a new dummy dataset- "Groceries_dataset.csv", which has more more dummy transactions than the previous dataset. The other problem was, when the write.csv() command is executed, it added quotes around the list of items, thus making it a single string. I have added the qoute = FALSE parameter in write.csv. This ensures that the list of items are now distinct and separated by commas. 
You can now play around with the support and confidence threshold values to control the number of rules you want.
Hope this helps. Please let me know if you run into any more issues.
Thanks!
